storage:
  cls: postgresql
  db: postgresql:///?service=swh-storage-replica
  objstorage:
    cls: filtered
    storage_conf:
      cls: remote
      url: http:/nginx:5080/objstorage
    filters_conf:
      - type: readonly
