version: '2'

services:
  swh-storage-db:
    image: postgres:10
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: swh-storage
  swh-storage:
    build: ./dockerfiles/swh-storage
    image: swh/storage
    ports:
    - 5002:5002
    depends_on:
      - swh-storage-db
      - swh-objstorage
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: swh-storage
      PGHOST: swh-storage-db
      PGUSER: postgres
  swh-objstorage:
    build: ./dockerfiles/swh-objstorage
    image: swh/objstorage
    ports:
    - 5003:5003
