version: '2'

services:
  cassandra-seed:
    # This container starts a Cassandra instance that must be used as the
    # contact-point for clients. This container will then make the client
    # discover other cassandra containers.
    # This container must not be scaled up; scale up th 'cassandra'
    # container instead.
    image: cassandra
    env_file:
    - ./env/cassandra.env
    entrypoint: /swh_entrypoint.sh
    volumes:
        - "./services/cassandra/swh_entrypoint.sh:/swh_entrypoint.sh:ro"
        - "./conf/cassandra.yaml:/cassandra.yaml:ro"
  cassandra:
    # Additional Cassandra instance(s), which may be scaled up, but not
    # down. They will automatically connect to 'cassandra-seed', and
    # 'cassandra-seed' will tell clients to connect to these 'cassandra'
    # containers to load-balance.
    image: cassandra
    entrypoint: /swh_entrypoint.sh
    volumes:
        - "./services/cassandra/swh_entrypoint.sh:/swh_entrypoint.sh:ro"
        - "./conf/cassandra.yaml:/cassandra.yaml:ro"
    env_file:
    - ./env/cassandra.env
