version: '2.0'

services:

  pgsql-storage:
    image: swh-storage-pg
    environment:
      POSTGRES_PASSWORD: testpassword

  swh-storage:
    image: swh-storage
    ports:
    - 5002:5002

  swh-objstorage:
    image: swh-objstorage
    ports:
    - 5003:5003
