version: '2'

services:

  amqp:
    image: rabbitmq:3.6-management
    ports:
      - 5072:5672

#  flower:
#    image: mher/flower
#    command: --broker=amqp://guest:guest@amqp:5672// --url_prefix=flower
#    ports:
#      - 5055:5555
#    depends_on:
#      - amqp

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "5092:9092"
    env_file: ./env/kafka.env
    depends_on:
      - zookeeper

  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "5093:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: random-secret
    command: -Dpidfile.path=/dev/null

  prometheus:
    image: prom/prometheus
    command:
      # Needed for the reverse-proxy
      - "--web.external-url=/prometheus"
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - "./conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    restart: unless-stopped

  prometheus-statsd-exporter:
    image: prom/statsd-exporter
    command:
      - "--statsd.mapping-config=/etc/prometheus/statsd-mapping.yml"
    volumes:
      - "./conf/prometheus-statsd-mapping.yml:/etc/prometheus/statsd-mapping.yml:ro"
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    restart: unless-stopped
    environment:
      GF_SERVER_ROOT_URL: http://localhost:5080/grafana
    volumes:
      - "./conf/grafana/provisioning:/etc/grafana/provisioning:ro"
      - "./conf/grafana/dashboards:/var/lib/grafana/dashboards"

  nginx:
    image: nginx
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 5080:5080

# Scheduler

  swh-scheduler-db:
    image: postgres:11
    env_file:
      - ./env/scheduler-db.env
    environment:
      # unset PGHOST as db service crashes otherwise
      PGHOST:

  swh-scheduler-api:
    image: swh/stack
    build: ./
    env_file:
      - ./env/scheduler-db.env
      - ./env/scheduler.env
    entrypoint: /swh-scheduler-api/entrypoint.sh
    environment:
      SWH_CONFIG_FILENAME: /scheduler.yml
      SWH_SCHEDULER_CONFIG_FILE: /scheduler.yml
    depends_on:
      - swh-scheduler-db
    ports:
      - 5008:5008
    volumes:
      - "./conf/scheduler.yml:/scheduler.yml:ro"

  swh-scheduler-listener:
    image: swh/stack
    build: ./
    entrypoint: /swh-scheduler-worker/entrypoint.sh
    env_file:
      - ./env/scheduler-db.env
      - ./env/scheduler.env
    environment:
      SWH_CONFIG_FILENAME: /scheduler.yml
      SWH_SCHEDULER_CONFIG_FILE: /scheduler.yml
    command: listener
    depends_on:
      - swh-scheduler-api
      - amqp
    volumes:
      - "./conf/scheduler.yml:/scheduler.yml:ro"

  swh-scheduler-runner:
    image: swh/stack
    build: ./
    entrypoint: /swh-scheduler-worker/entrypoint.sh
    env_file:
      - ./env/scheduler-db.env
      - ./env/scheduler.env
    environment:
      SWH_CONFIG_FILENAME: /scheduler.yml
      SWH_SCHEDULER_CONFIG_FILE: /scheduler.yml
    command: runner -p 10
    depends_on:
      - swh-scheduler-api
      - amqp
    volumes:
      - "./conf/scheduler.yml:/scheduler.yml:ro"

# Graph storage

  swh-storage-db:
    image: postgres:11
    env_file:
      - ./env/storage-db.env
    environment:
      # unset PGHOST as db service crashes otherwise
      PGHOST:

  swh-storage:
    build: ./
    image: swh/stack
    entrypoint: /swh-storage/entrypoint.sh
    ports:
      - 5002:5002
    depends_on:
      - swh-storage-db
      - swh-objstorage
    env_file:
      - ./env/storage-db.env
    environment:
      SWH_CONFIG_FILENAME: /storage.yml
    volumes:
      - "./conf/storage.yml:/storage.yml:ro"

# Object storage

  swh-objstorage:
    build: ./
    image: swh/stack
    entrypoint: /swh-objstorage/entrypoint.sh
    ports:
      - 5003:5003
    environment:
      SWH_CONFIG_FILENAME: /objstorage.yml
    volumes:
      - "./conf/objstorage.yml:/objstorage.yml:ro"

# Indexer storage

  swh-idx-storage-db:
    image: postgres:11
    env_file:
      - ./env/indexers-db.env
    environment:
      # unset PGHOST as db service crashes otherwise
      PGHOST:

  swh-idx-storage:
    build: ./
    image: swh/stack
    entrypoint: /swh-indexer-storage/entrypoint.sh
    ports:
      - 5007:5007
    depends_on:
      - swh-idx-storage-db
    env_file:
      - ./env/indexers-db.env
    environment:
      SWH_CONFIG_FILENAME: /indexer_storage.yml
    volumes:
      - "./conf/indexer_storage.yml:/indexer_storage.yml:ro"

# Web interface

  swh-web:
    build: ./
    image: swh/stack
    entrypoint: /swh-web/entrypoint.sh
    ports:
      - 5004:5004
    depends_on:
      - swh-objstorage
      - swh-storage
      - swh-idx-storage
    environment:
      VERBOSITY: 3
      DJANGO_SETTINGS_MODULE: swh.web.settings.development
      SWH_CONFIG_FILENAME: /web.yml
      PYTHONPATH: /tmp/swh
    volumes:
      - "./conf/web.yml:/web.yml:ro"

  swh-deposit-db:
    image: postgres:11
    env_file:
      - ./env/deposit-db.env
    environment:
      # unset PGHOST as db service crashes otherwise
      PGHOST:

  swh-deposit:
    build: ./
    entrypoint: /swh-deposit/entrypoint.sh
    image: swh/stack
    ports:
      - 5006:5006
    depends_on:
      - swh-deposit-db
      - swh-scheduler-api
    env_file:
      - ./env/deposit-db.env
      - ./env/deposit.env
    volumes:
      - "./conf/deposit.yml:/deposit.yml:ro"

  swh-vault-db:
    image: postgres:11
    env_file:
      - ./env/vault-db.env
    environment:
      # unset PGHOST as db service crashes otherwise
      PGHOST:

  swh-vault-api:
    build: ./
    image: swh/stack
    entrypoint: /swh-vault/entrypoint.sh
    env_file:
      - ./env/vault-db.env
    environment:
      SWH_CONFIG_FILENAME: /vault-api.yml
    command: server
    ports:
      - 5005:5005
    depends_on:
      - swh-vault-db
      - swh-objstorage
      - swh-storage
      - swh-scheduler-api
    volumes:
      - "./conf/vault-api.yml:/vault-api.yml:ro"

  swh-vault-worker:
    build: ./
    image: swh/stack
    entrypoint: /swh-vault/entrypoint.sh
    command: worker
    environment:
      SWH_CONFIG_FILENAME: /cooker.yml
    depends_on:
      - swh-vault-api
      - swh-storage
    volumes:
      - "./conf/vault-worker.yml:/cooker.yml:ro"


# Lister Celery workers

  swh-listers-db:
    image: postgres:11
    env_file:
      - ./env/listers-db.env
    environment:
      # unset PGHOST as db service crashes otherwise
      PGHOST:

  swh-lister:
    image: swh/stack
    build: ./
    entrypoint: /swh-listers-worker/entrypoint.sh
    env_file:
      - ./env/listers-db.env
      - ./env/listers.env
    user: swh
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
      SWH_WORKER_INSTANCE: listers
      SWH_CONFIG_FILENAME: /lister.yml
    depends_on:
      - swh-listers-db
      - swh-scheduler-api
      - swh-scheduler-runner
      - swh-storage
      - amqp
    volumes:
      - "./conf/lister.yml:/lister.yml:ro"

# Loader Celery workers

  swh-loader:
    image: swh/stack
    build: ./
    entrypoint: /swh-loaders-worker/entrypoint.sh
    env_file:
      - ./env/listers.env
    user: swh
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
      SWH_WORKER_INSTANCE: loader
      SWH_CONFIG_FILENAME: /loader.yml
    depends_on:
      - swh-storage
      - amqp
    volumes:
      - "./conf/loader.yml:/loader.yml:ro"

# Indexer Celery workers

  swh-indexer:
    image: swh/stack
    build: ./
    user: swh
    entrypoint: /swh-indexer-worker/entrypoint.sh
    env_file:
      - ./env/indexers-db.env
      - ./env/indexers.env
    environment:
      STATSD_HOST: prometheus-statsd-exporter
      STATSD_PORT: 9125
    depends_on:
      - swh-scheduler-runner
      - swh-idx-storage
      - swh-storage
      - swh-objstorage
      - amqp
    volumes:
      - "./conf/indexer.yml:/indexer.yml:ro"

# Journal related

  swh-storage-listener:
    image: swh/stack
    build: ./
    entrypoint: /swh-storage-listener/entrypoint.sh
    env_file:
      - ./env/storage-db.env
    depends_on:
      - swh-storage-db
      - kafka
    volumes:
      - "./conf/storage_listener.yml:/etc/softwareheritage/storage/listener.yml:ro"

  swh-journal-publisher:
    image: swh/stack
    build: ./
    entrypoint: /swh-journal-publisher/entrypoint.sh
    environment:
      SWH_CONFIG_FILENAME: /journal_publisher.yml
    depends_on:
      - kafka
      - swh-storage-listener
    volumes:
      - "./conf/journal_publisher.yml:/journal_publisher.yml:ro"

  swh-journal-client:
    image: swh/stack
    build: ./
    entrypoint: /swh-journal-client/entrypoint.sh
    depends_on:
      - swh-journal-publisher
    volumes:
      - "./conf/journal_client.yml:/etc/softwareheritage/journal/logger.yml:ro"

  swh-indexer-journal-client:
    image: swh/stack
    build: ./
    entrypoint: /swh-indexer-journal-client/entrypoint.sh
    depends_on:
      - swh-journal-publisher
      - swh-scheduler-api
    volumes:
      - "./conf/indexer_journal_client.yml:/etc/softwareheritage/indexer/journal_client.yml:ro"
