#    -*- mode: Makefile -*-

PYMODULE := $(shell basename `pwd` | sed 's/-/./g')

EXTRA_DIRS := $(shell test -d bin && echo bin)

NOSE = nosetests3
NOSEFLAGS = -v
FLAKE = flake8
FLAKEFLAGS =

all:

.PHONY: test
test:
	$(NOSE) $(NOSEFLAGS)

.PHONY: coverage
coverage:
	$(NOSE) $(NOSEFLAGS) --with-coverage --cover-package $(PYMODULE)

.PHONY: check
check:
	$(FLAKE) $(FLAKEFLAGS) swh $(EXTRA_DIRS)
