defaults:
  timer_type: histogram
  buckets:
    - .005
    - .01
    - .025
    - .05
    - .1
    - .25
    - .5
    - .75
    - 1
    - 2
    - 5
    - 10
    - 15
    - 30
    - 45
    - 60
    - 120
    - 300
    - 600
    - 900
    - 1800
    - 2700
    - 3600
    - 7200
