apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: swh-environment
build:
  local:
    useBuildkit: true
    concurrency: 2
  artifacts:
  - image: swh/stack-base
    context: docker
    docker:
      dockerfile: Dockerfile
  - image: swh/objstorage
    docker:
      dockerfile: Dockerfile.objstorage
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/storage
    docker:
      dockerfile: Dockerfile.storage
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/scheduler
    docker:
      dockerfile: Dockerfile.scheduler
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/webapp
    docker:
      dockerfile: Dockerfile.webapp
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/loaders
    docker:
      dockerfile: Dockerfile.loaders
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/listers
    docker:
      dockerfile: Dockerfile.listers
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/grafana
    docker:
      dockerfile: Dockerfile.grafana
  - image: swh/search
    docker:
      dockerfile: Dockerfile.search
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/counters
    docker:
      dockerfile: Dockerfile.counters
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/indexers
    docker:
      dockerfile: Dockerfile.indexers
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/vault
    docker:
      dockerfile: Dockerfile.vault
    requires:
      - image: swh/stack-base
        alias: BASE
deploy:
  kubectl:
    manifests:
    - kubernetes/01-journal.yml
    - kubernetes/02-monitoring.yml
    - kubernetes/05-storage-db.yml
    - kubernetes/10-objstorage.yml
    - kubernetes/11-storage.yml
    - kubernetes/15-scheduler-db.yml
    - kubernetes/16-rabbitmq.yml
    - kubernetes/20-scheduler.yml
    - kubernetes/21-scheduler-runner.yml
    - kubernetes/22-scheduler-listener.yml
    - kubernetes/23-scheduler-journal-client.yml
    - kubernetes/29-web-db.yml
    - kubernetes/30-webapp.yml
    - kubernetes/40-loaders.yml
    - kubernetes/45-listers.yml
    - kubernetes/50-elasticsearch.yml
    - kubernetes/55-search.yml
    - kubernetes/56-search-journal-client.yml
    - kubernetes/60-redis.yml
    - kubernetes/61-counters.yml
    - kubernetes/62-counters-journal-client.yml
    - kubernetes/70-idx-storage-db.yml
    - kubernetes/71-idx-storage.yml
    - kubernetes/72-indexers.yml
    - kubernetes/73-indexer-journal-client.yml
    - kubernetes/80-vault-db.yml
    - kubernetes/81-vault.yml
    - kubernetes/82-cookers.yml
    - kubernetes/90-deposit-db.yml
