apiVersion: skaffold/v2beta13
kind: Config
metadata:
  name: swh-environment
build:
  artifacts:
  - image: swh/stack-base
    docker:
      dockerfile: Dockerfile
  - image: swh/objstorage
    docker:
      dockerfile: Dockerfile.objstorage
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/storage
    docker:
      dockerfile: Dockerfile.storage
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/scheduler
    docker:
      dockerfile: Dockerfile.scheduler
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/webapp
    docker:
      dockerfile: Dockerfile.webapp
    requires:
      - image: swh/stack-base
        alias: BASE
  - image: swh/loaders
    docker:
      dockerfile: Dockerfile.loaders
    requires:
      - image: swh/stack-base
        alias: BASE
deploy:
  kubectl:
    manifests:
    - kubernetes/01-journal.yml
    - kubernetes/05-storage-db.yml
    - kubernetes/10-objstorage.yml
    - kubernetes/11-storage.yml
    - kubernetes/15-scheduler-db.yml
    - kubernetes/16-rabbitmq.yml
    - kubernetes/20-scheduler.yml
    - kubernetes/29-web-db.yml
    - kubernetes/30-webapp.yml
    - kubernetes/40-loaders.yml
