storage:
  cls: remote
  url: http://swh-mirror-storage:5002

journal_client:
  cls: kafka
  brokers:
    - kafka
  prefix: swh.journal.objects
  group_id: swh.storage.mirror.replayer
  privileged: true
