storage:
  cls: pipeline
  steps:
    - cls: filter
    - cls: retry
    - cls: remote
      url: http://nginx-mirror/storage

journal_client:
  cls: kafka
  brokers:
    - kafka
  prefix: swh.journal.objects
  group_id: swh.storage.mirror.replayer
  privileged: true
  object_types:
    - content
    - directory
    - extid
    - origin
    - origin_visit
    - origin_visit_status
    - raw_extrinsic_metadata
    - release
    - revision
    - skipped_content
    - snapshot
