storage:
  cls: postgresql
  db: postgresql:///?service=swh-storage-mirror
  objstorage:
    cls: filtered
    storage_conf:
      cls: remote
      url: http://swh-objstorage-mirror:5003/
    filters_conf:
      - type: readonly
