storage:
  cls: remote
  url: http://swh-mirror-storage:5002/
scheduler:
  cls: remote
  url: http://swh-mirror-scheduler:5008/
vault:
  cls: postgresql
  db: postgresql:///?service=swh-mirror-vault
cache:
  cls: pathslicing
  root: /srv/softwareheritage/vault
  slicing: 0:5
