storage:
  cls: remote
  url: http://nginx-mirror/storage
vault:
  cls: remote
  url: http://nginx-mirror/vault
celery:
  broker_heartbeat: null
  task_broker: amqp://guest:guest@amqp-mirror/
  task_modules:
    - swh.vault.cooking_tasks
  task_queues:
    - swh.vault.cooking_tasks.SWHBatchCookingTask
    - swh.vault.cooking_tasks.SWHCookingTask

max_bundle_size: 536870912
