# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
        - localhost:9090
    metrics_path: /prometheus/metrics

  - job_name: statsd-exporter
    static_configs:
    - targets:
        - prometheus-statsd-exporter:9102

  - job_name: jmx-exporter-cassandra
    static_configs:
    - targets:
        - prometheus-jmx-exporter-cassandra:5556
