version: "3.8"

services:

  nginx-replica:
    image: nginx
    volumes:
      - "./conf/replica/nginx.conf:/etc/nginx/nginx.conf:ro"
    ports:
      - 5082:80

  swh-replica-storage-db:
    image: postgres:16
    environment:
      POSTGRES_DB: swh-replica-storage
      POSTGRES_PASSWORD: testpassword

  swh-replica-storage:
    image: swh/stack
    build: ./
    depends_on:
      - swh-storage-db
      - swh-replica-storage-db
      - swh-objstorage
      - prometheus-statsd-exporter
    env_file:
      - ./env/common_python.env
      - ./env/storage-replica.env
    environment:
      SWH_CONFIG_FILENAME: /storage.yml
      STORAGE_BACKEND: postgresql
      DB_FLAVOR: read_replica
      RPC_PORT: 5002
    entrypoint: /entrypoint.sh
    command: rpc
    volumes:
      - "./conf/replica/storage.yml:/storage.yml:ro"
      - "./services/swh-storage/entrypoint.sh:/entrypoint.sh:ro"

  # override storage db to enable wal_level=logical
  swh-storage-db:
    command: postgres -c wal_level=logical

  # a dedicated swh-web db
  swh-replica-web-db:
    image: postgres:16
    environment:
      POSTGRES_DB: swh-replica-web
      POSTGRES_PASSWORD: testpassword
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"

  # a dedicated swh-web
  swh-replica-web:
    build: ./
    image: swh/stack
    depends_on:
      - swh-replica-storage
      - swh-replica-web-db
      - prometheus-statsd-exporter
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-replica-web
      VERBOSITY: 3
      DJANGO_SETTINGS_MODULE: swh.web.settings.production
      SWH_CONFIG_FILENAME: /web.yml
    entrypoint: /entrypoint.sh
    volumes:
      - "./conf/replica/web.yml:/web.yml:ro"
      - "./services/swh-web/entrypoint.sh:/entrypoint.sh:ro"
      - "./assets/replica/:/replica/:ro"

  swh-replica-vault-db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: swh-replica-vault
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"

  swh-replica-vault:
    image: swh/stack
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-replica-vault
      SWH_CONFIG_FILENAME: /vault.yml
      RPC_PORT: 5005
    entrypoint: /entrypoint.sh
    command: rpc
    depends_on:
      - swh-replica-vault-db
      - swh-objstorage
      - swh-replica-storage
      - swh-replica-scheduler
      - prometheus-statsd-exporter
    volumes:
      - "./conf/replica/vault.yml:/vault.yml:ro"
      - "./services/swh-vault/entrypoint.sh:/entrypoint.sh:ro"

  swh-replica-vault-worker:
    image: swh/stack
    build: ./
    entrypoint: /entrypoint.sh
    command: worker
    env_file:
      - ./env/common_python.env
      - ./env/workers.env
    environment:
      SWH_CONFIG_FILENAME: /cooker.yml
    depends_on:
      - swh-replica-vault
      - swh-replica-storage
      - prometheus-statsd-exporter
    volumes:
      - "./conf/replica/vault-worker.yml:/cooker.yml:ro"
      - "./services/swh-vault/entrypoint.sh:/entrypoint.sh:ro"

  swh-replica-scheduler-db:
    image: postgres:16
    environment:
      POSTGRES_DB: swh-replica-scheduler
      POSTGRES_PASSWORD: testpassword
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"

  swh-replica-scheduler:
    image: swh/stack
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-replica-scheduler
      SWH_CONFIG_FILENAME: /scheduler.yml
      SWH_SCHEDULER_CONFIG_FILE: /scheduler.yml
      RPC_PORT: 5008
      BROKER_URL: amqp://amqp-replica/
    entrypoint: /entrypoint.sh
    command: rpc
    depends_on:
      - swh-replica-scheduler-db
      - prometheus-statsd-exporter
    volumes:
      - "./conf/replica/scheduler.yml:/scheduler.yml:ro"
      - "./services/swh-scheduler/entrypoint.sh:/entrypoint.sh:ro"

  swh-replica-scheduler-listener:
    image: swh/stack
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-replica-scheduler
      SWH_CONFIG_FILENAME: /scheduler.yml
      SWH_SCHEDULER_CONFIG_FILE: /scheduler.yml
      SWH_WORKER_INSTANCE: scheduler
      BROKER_URL: amqp://amqp-replica/
      APP: swh.scheduler.celery_backend.config.app
    entrypoint: /entrypoint.sh
    command: worker start-listener
    depends_on:
      - swh-replica-scheduler
      - amqp-replica
      - prometheus-statsd-exporter
    volumes:
      - "./conf/replica/scheduler.yml:/scheduler.yml:ro"
      - "./services/swh-scheduler/entrypoint.sh:/entrypoint.sh:ro"

  swh-replica-scheduler-runner:
    image: swh/stack
    build: ./
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-replica-scheduler
      SWH_CONFIG_FILENAME: /scheduler.yml
      SWH_SCHEDULER_CONFIG_FILE: /scheduler.yml
      SWH_WORKER_INSTANCE: scheduler
      APP: swh.scheduler.celery_backend.config.app
    entrypoint: /entrypoint.sh
    command: worker start-runner --period 10
    depends_on:
      - swh-replica-scheduler
      - amqp-replica
      - prometheus-statsd-exporter
    volumes:
      - "./conf/replica/scheduler.yml:/scheduler.yml:ro"
      - "./services/swh-scheduler/entrypoint.sh:/entrypoint.sh:ro"

  amqp-replica:
    image: rabbitmq:3.6-management
