version: "2.1"

services:
  swh-graphql:
    image: swh/stack
    build: ./
    depends_on:
      - swh-storage
    ports:
      - 5013:5013
    environment:
      SWH_CONFIG_FILENAME: /graphql.yml
    env_file:
      - ./env/common_python.env
    volumes:
      - "./conf/graphql.yml:/graphql.yml:ro"
      - "./services/swh-graphql/entrypoint.sh:/entrypoint.sh:ro"
    entrypoint: /entrypoint.sh
