version: "2.1"

services:

  # create a dedicated db for the mirror
  swh-storage-mirror-db:
    image: postgres:16
    environment:
      POSTGRES_DB: swh-storage-mirror
      POSTGRES_PASSWORD: testpassword

  # and an RPC server
  swh-storage-mirror:
    image: swh/stack
    build: ./
    depends_on:
      - swh-storage-mirror-db
      - swh-objstorage
    env_file:
      - ./env/common_python.env
    environment:
      DB_FLAVOR: mirror
      POSTGRES_DB: swh-storage-mirror
      STORAGE_BACKEND: postgresql
      SWH_CONFIG_FILENAME: /storage-mirror.yml
      RPC_PORT: 5002
    entrypoint: /entrypoint.sh
    command: rpc
    volumes:
      - "./conf/storage-mirror.yml:/storage-mirror.yml:ro"
      - "./services/swh-storage/entrypoint.sh:/entrypoint.sh:ro"

  # a dedicated swh-web db
  swh-web-mirror-db:
    image: postgres:16
    environment:
      POSTGRES_DB: swh-web-mirror
      POSTGRES_PASSWORD: testpassword
    volumes:
      - "./services/initdb.d:/docker-entrypoint-initdb.d"

  # a dedicated swh-web
  swh-web-mirror:
    build: ./
    image: swh/stack
    depends_on:
      - swh-storage-mirror
      - swh-web-mirror-db
    env_file:
      - ./env/common_python.env
    environment:
      POSTGRES_DB: swh-web-mirror
      VERBOSITY: 3
      DJANGO_SETTINGS_MODULE: swh.web.settings.production
      SWH_CONFIG_FILENAME: /web-mirror.yml
    entrypoint: /entrypoint.sh
    volumes:
      - "./conf/web-mirror.yml:/web-mirror.yml:ro"
      - "./services/swh-web/entrypoint.sh:/entrypoint.sh:ro"

  # and the background process that keeps the mirror in sync with the
  # main graph
  swh-storage-mirror-replayer:
    image: swh/stack
    build: ./
    depends_on:
      - swh-storage-mirror-db
      - swh-objstorage
    env_file:
      - ./env/common_python.env
    environment:
      DB_FLAVOR: mirror
      POSTGRES_DB: swh-storage-mirror
      SWH_CONFIG_FILENAME: /storage-mirror.yml
      LOG_LEVEL: DEBUG
    entrypoint: /entrypoint.sh
    command: replayer
    volumes:
      - "./conf/storage-mirror.yml:/storage-mirror.yml:ro"
      - "./services/swh-storage/entrypoint.sh:/entrypoint.sh:ro"
      - "../swh-storage:/src/swh-storage"

  swh-journal-backfiller:
    image: swh/stack
    build: ./
    entrypoint: /entrypoint.sh
    command: backfiller
    environment:
      POSTGRES_DB: swh-storage
      SWH_CONFIG_FILENAME: /storage-mirror-backfiller.yml
    depends_on:
      - swh-storage-db
      - kafka
    volumes:
      - "./conf/storage-mirror-backfiller.yml:/storage-mirror-backfiller.yml:ro"
      - "./services/swh-storage/entrypoint.sh:/entrypoint.sh:ro"
