version: "2.1"

services:
  elasticsearch:
    env_file:
      - ./env/elasticsearch.env
    image: elastic/elasticsearch:7.15.2
    environment:
      - ingest.geoip.downloader.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  swh-search:
    depends_on:
      - elasticsearch
    volumes:
      - "./conf/search.yml:/search.yml:ro"

volumes:
  elasticsearch-data:
