# config file version
apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://localhost:5080/prometheus
    access: direct
    isDefault: true
    version: 1
    editable: false
