---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deposit-loaders
data:
  config.yml: |
    default_filename: archive.tar
    storage:
      cls: pipeline
      steps:
        - cls: buffer
          min_batch_size:
            content: 10000
            content_bytes: 104857600
            directory: 1000
            revision: 1000
        - cls: filter
        - cls: retry
        - cls: remote
          url: http://storage:5002/

    celery:
      task_broker: amqp://guest:guest@amqp//
      task_queues:
        - swh.loader.package.deposit.tasks.LoadDeposit
        - swh.deposit.loader.tasks.ChecksDepositTsk

    deposit:
      url: http://deposit:5006/1/private
      auth:
        username: test
        password: test

    url: http://deposit:5006
  entrypoint-init.sh: |
    #!/bin/bash

    set -e

    # echo Waiting for RabbitMQ to start
    wait-for-it amqp:5672 -s --timeout=0
    wait-for-it deposit:5006 -s --timeout=0
    wait-for-it scheduler:5008 -s --timeout=0

    # echo Register task types in scheduler database
    swh scheduler --url http://scheduler:5008 task-type register
  entrypoint.sh: |
    #!/bin/bash

    set -e

    echo Starting the swh Celery worker
    exec python -m celery \
                --app=swh.scheduler.celery_backend.config.app \
                worker \
                --pool=prefork --events \
                --concurrency=${CONCURRENCY} \
                --max-tasks-per-child=${MAX_TASKS_PER_CHILD} \
                -Ofair --loglevel=${LOGLEVEL} \
                --hostname "${HOSTNAME}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deposit-loaders
  labels:
    app: deposit-loaders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deposit-loaders
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: deposit-loaders
    spec:
      initContainers:
        - name: loaders-deposit-init
          image: swh/loaders:latest
          imagePullPolicy: Always
          command:
            - /entrypoint.sh
          volumeMounts:
            - name: config
              mountPath: /etc/softwareheritage/config.yml
              subPath: config.yml
              readOnly: true
            - name: config
              mountPath: /entrypoint.sh
              subPath: entrypoint-init.sh
              readOnly: true
      containers:
      - name: deposit-loaders
        image: swh/loaders:latest
        imagePullPolicy: Always
        command:
          - /entrypoint.sh
        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        lifecycle:
          preStop:
           exec:
             command: ["kill", "1"]
        env:
        - name: CONCURRENCY
          value: "1"
        - name: MAX_TASKS_PER_CHILD
          value: "5"
        - name: LOGLEVEL
          value: "INFO"
        - name: SWH_CONFIG_FILENAME
          value: /etc/softwareheritage/config.yml
        volumeMounts:
          - name: config
            mountPath: /etc/softwareheritage/config.yml
            subPath: config.yml
            readOnly: true
          - name: config
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: deposit-loaders
            defaultMode: 0777
