---
apiVersion: v1
kind: ConfigMap
metadata:
  name: idx-storage
data:
  config.yml: |
    indexer_storage:
      cls: local
      db: postgresql:///?service=swh
      journal_writer:
        cls: kafka
        args:
          brokers:
            - kafka
          prefix: swh.journal.indexed
          client_id: swh.idx_storage.master
          producer_config:
            message.max.bytes: 1000000000
  entrypoint-init-db.sh: |
    #!/bin/bash

    set -e

    source /srv/softwareheritage/utils/pgsql.sh

    echo -n "waiting for database availability"
    wait_pgsql ${PGDATABASE}

    echo Database setup
    echo Creating extensions...
    swh db init-admin --db-name ${PGDATABASE} indexer

    echo Initializing the database...
    swh db init --db-name ${PGDATABASE} indexer

  entrypoint.sh: |
    #!/bin/bash

    set -e

    source /srv/softwareheritage/utils/pgsql.sh
    setup_pgsql

    echo Starting the swh-indexer-storage RPC server
    exec gunicorn --bind 0.0.0.0:5007 \
          --reload \
          --threads 4 \
          --workers 2 \
          --log-level ${LOGLEVEL} \
          --timeout 3600 \
          --config 'python:swh.core.api.gunicorn_config' \
          'swh.indexer.storage.api.server:make_app_from_configfile()'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: idx-storage
  labels:
    app: idx-storage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idx-storage
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: idx-storage
    spec:
      initContainers:
        - name: idx-storage-init
          image: swh/indexers:latest
          imagePullPolicy: Always
          command:
            - /entrypoint.sh
          env:
          - name: PGHOST
            value: "idx-storage-db"
          - name: PGUSER
            valueFrom:
              configMapKeyRef:
                name: idx-storage-db
                key: POSTGRES_USER
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: idx-storage-db
                key: POSTGRES_PASSWORD
          - name: PGDATABASE
            valueFrom:
              configMapKeyRef:
                name: idx-storage-db
                key: POSTGRES_DB
          - name: SWH_CONFIG_FILENAME
            value: /etc/softwareheritage/config.yml
          volumeMounts:
            - name: db-password
              mountPath: /run/secrets/postgres-password
              subPath: POSTGRES_PASSWORD
              readOnly: true
            - name: config
              mountPath: /etc/softwareheritage/config.yml
              subPath: config.yml
              readOnly: true
            - name: config
              mountPath: /entrypoint.sh
              subPath: entrypoint-init-db.sh
              readOnly: true
      containers:
      - name: idx-storage
        image: swh/indexers:latest
        imagePullPolicy: Always
        command:
          - /entrypoint.sh
        ports:
        - containerPort: 5007
        readinessProbe:
          httpGet:
            path: /
            port: 5007
            scheme: "HTTP"
          initialDelaySeconds: 0
          failureThreshold: 2
          periodSeconds: 10
        startupProbe:
          httpGet:
            path: /
            port: 5007
            scheme: "HTTP"
          initialDelaySeconds: 5
          failureThreshold: 30
          periodSeconds: 1
        env:
        - name: PORT
          value: "5007"
        - name: STATSD_HOST
          value: "prometheus-statsd-exporter"
        - name: STATSD_PORT
          value: "9125"
        - name: POSTGRES_PASSWORD_FILE
          value: "/run/secrets/postgres-password"
        - name: PGHOST
          value: "idx-storage-db"
        - name: PGUSER
          valueFrom:
            configMapKeyRef:
              name: idx-storage-db
              key: POSTGRES_USER
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: idx-storage-db
              key: POSTGRES_PASSWORD
        - name: PGDATABASE
          valueFrom:
            configMapKeyRef:
              name: idx-storage-db
              key: POSTGRES_DB
        - name: SWH_CONFIG_FILENAME
          value: /etc/softwareheritage/config.yml
        - name: LOGLEVEL
          value: INFO
        volumeMounts:
          - name: db-password
            mountPath: /run/secrets/postgres-password
            subPath: POSTGRES_PASSWORD
            readOnly: true
          - name: config
            mountPath: /etc/softwareheritage/config.yml
            subPath: config.yml
            readOnly: true
          - name: config
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
            readOnly: true
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1536Mi"
            cpu: "300m"
      volumes:
        - name: config
          configMap:
            name: idx-storage
            defaultMode: 0777
        - name: db-password
          secret:
            secretName: idx-storage-db
---
apiVersion: v1
kind: Service
metadata:
  name: idx-storage
spec:
  type: ClusterIP
  selector:
    app: idx-storage
  ports:
    - port: 5007
      targetPort: 5007
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idx-storage
spec:
  rules:
  - host: idx-storage.default
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: idx-storage
            port:
              number: 5007
