---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indexers
data:
  config.yml: |
    storage:
      cls: remote
      url: http://storage:5002/
    objstorage:
      cls: remote
      url: http://objstorage:5003/
    indexer_storage:
      cls: remote
      url: http://idx-storage:5007/
    scheduler:
      cls: remote
      url: http://scheduler:5008/
    celery:
      task_broker: amqp://guest:guest@amqp//
      task_modules:
        - swh.indexer.tasks
      task_queues:
        - swh.indexer.tasks.OriginMetadata
    tools:
      name: swh-metadata-detector
      version: 0.0.2
      configuration: {}

  entrypoint-init.sh: |
    #!/bin/bash

    set -e

    # echo Waiting for RabbitMQ to start
    wait-for-it amqp:5672 -s --timeout=0

    # echo Register task types in scheduler database
    wait-for-it scheduler:5008 -s --timeout=0
    swh scheduler --url http://scheduler:5008 task-type register

    # Wait for services to be up
    wait-for-it idx-storage:5007 -s --timeout=0
    wait-for-it storage:5002 -s --timeout=0
    wait-for-it objstorage:5003 -s --timeout=0

  entrypoint.sh: |
    #!/bin/bash

    set -e

    echo Starting the swh Celery worker
    exec python -m celery \
                --app=swh.scheduler.celery_backend.config.app \
                worker \
                --pool=prefork --events \
                --concurrency=${CONCURRENCY} \
                --max-tasks-per-child=${MAX_TASKS_PER_CHILD} \
                -Ofair --loglevel=${LOGLEVEL} \
                --hostname "${HOSTNAME}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexers
  labels:
    app: indexers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexers
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: indexers
    spec:
      initContainers:
        - name: indexers-init
          image: swh/indexers:latest
          imagePullPolicy: Always
          command:
            - /entrypoint.sh
          volumeMounts:
            - name: config
              mountPath: /etc/softwareheritage/config.yml
              subPath: config.yml
              readOnly: true
            - name: config
              mountPath: /entrypoint.sh
              subPath: entrypoint-init.sh
              readOnly: true
      containers:
      - name: indexers
        image: swh/indexers:latest
        imagePullPolicy: Always
        command:
          - /entrypoint.sh
        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "800m"
        lifecycle:
          preStop:
           exec:
             command: ["kill", "1"]
        env:
        - name: CONCURRENCY
          value: "1"
        - name: MAX_TASKS_PER_CHILD
          value: "5"
        - name: LOGLEVEL
          value: "INFO"
        - name: SWH_CONFIG_FILENAME
          value: /etc/softwareheritage/config.yml
        volumeMounts:
          - name: config
            mountPath: /etc/softwareheritage/config.yml
            subPath: config.yml
            readOnly: true
          - name: config
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: indexers
            defaultMode: 0777
