---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cookers
data:
  config.yml: |
    storage:
      cls: remote
      url: http://storage:5002/
    vault:
      cls: remote
      url: http://vault:5005/
    celery:
      task_broker: amqp://guest:guest@amqp//
      task_modules:
        - swh.vault.cooking_tasks
      task_queues:
        - swh.vault.cooking_tasks.SWHBatchCookingTask
        - swh.vault.cooking_tasks.SWHCookingTask

    max_bundle_size: 536870912

  entrypoint-init.sh: |
    #!/bin/bash

    set -e

    # echo Waiting for RabbitMQ to start
    wait-for-it amqp:5672 -s --timeout=0

    # echo Register task types in scheduler database
    wait-for-it scheduler:5008 -s --timeout=0
    swh scheduler --url http://scheduler:5008 task-type register

    # Wait for services to be up
    wait-for-it vault:5005 -s --timeout=0
    wait-for-it storage:5002 -s --timeout=0

  entrypoint.sh: |
    #!/bin/bash

    set -e

    echo Starting the swh-vault Celery worker
    exec python -m celery \
                --app=swh.scheduler.celery_backend.config.app \
                worker \
                --pool=prefork --events \
                --concurrency=${CONCURRENCY} \
                --max-tasks-per-child=${MAX_TASKS_PER_CHILD} \
                -Ofair --loglevel=${LOGLEVEL} \
                --hostname "${HOSTNAME}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookers
  labels:
    app: cookers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookers
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cookers
    spec:
      initContainers:
        - name: cookers-init
          image: swh/vault:latest
          imagePullPolicy: Always
          command:
            - /entrypoint.sh
          volumeMounts:
            - name: config
              mountPath: /etc/softwareheritage/config.yml
              subPath: config.yml
              readOnly: true
            - name: config
              mountPath: /entrypoint.sh
              subPath: entrypoint-init.sh
              readOnly: true
      containers:
      - name: cookers
        image: swh/vault:latest
        imagePullPolicy: Always
        command:
          - /entrypoint.sh
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "3000Mi"
            cpu: "1200m"
        lifecycle:
          preStop:
           exec:
             command: ["kill", "1"]
        env:
        - name: CONCURRENCY
          value: "1"
        - name: MAX_TASKS_PER_CHILD
          value: "5"
        - name: LOGLEVEL
          value: "INFO"
        - name: SWH_CONFIG_FILENAME
          value: /etc/softwareheritage/config.yml
        volumeMounts:
          - name: config
            mountPath: /etc/softwareheritage/config.yml
            subPath: config.yml
            readOnly: true
          - name: config
            mountPath: /entrypoint.sh
            subPath: entrypoint.sh
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: cookers
            defaultMode: 0777
