counters:
  cls: remote
  url: http://nginx:5080/counters
journal:
  brokers:
    - kafka
  prefix: swh.journal.objects
  group_id: swh.counters.journal_client
  object_types:
    - content
    - directory
    - origin
    - origin_visit
    - origin_visit_status
    - release
    - revision
    - skipped_content
    - snapshot
