scheduler:
  cls: remote
  url: http://nginx:5080/scheduler

storage:
  cls: remote
  url: http://nginx:5080/storage

storage_metadata:
  cls: remote
  url: http://nginx:5080/storage

allowed_hosts:
  - "*"

private:
  secret_key: prod-in-docker
  db:
    host: swh-deposit-db
    port: 5432
    name: swh-deposit
    user: postgres
    password: testpassword
  media_root: /tmp/swh-deposit/uploads

extraction_dir: "/tmp/swh-deposit/archive/"

authentication_provider: keycloak
keycloak:
  server_url: http://nginx:5080/keycloak/auth/
  realm_name: SoftwareHeritage
cache_uri: memcache:11211

swh_authority_url: https://deposit.swh.example/
