storage:
  cls: remote
  url: http://swh-storage:5002

search:
  cls: remote
  url: http://swh-search:5010/

debug: yes

introspection: yes

max_query_cost:
  anonymous: 500

auth:
  server: https://auth.softwareheritage.org/auth/
  realm: SoftwareHeritageStaging
  client: swh-web
  cache:
    url: memory://
