# config is a bit messy here, generic db handling (swh.core.db) expect the
# main config section to named after the swh package (indexer) while the
# indexer storage service expect it to be indexer_storage

# this is used only for db setup
indexer:
  cls: postgresql
  db: postgresql:///?service=swh-idx-storage

indexer_storage:
  cls: postgresql
  db: postgresql:///?service=swh-idx-storage
  journal_writer:
    cls: kafka
    brokers:
      - kafka
    prefix: swh.journal.indexed
    client_id: swh.idx_storage.journal_writer
    producer_config:
      message.max.bytes: 1000000000
