storage:
  cls: remote
  url: http://swh-storage:5002/
objstorage:
  cls: remote
  url: http://swh-objstorage:5003/
indexer_storage:
  cls: remote
  url: http://swh-idx-storage:5007/
scheduler:
  cls: remote
  url: http://swh-scheduler:5008/
celery:
  broker_heartbeat: null
  task_broker: amqp://guest:guest@amqp//
  task_modules:
    - swh.indexer.tasks
  task_queues:
    - swh.indexer.tasks.ContentFossologyLicense
    - swh.indexer.tasks.ContentLanguage
    - swh.indexer.tasks.ContentMimetype
    - swh.indexer.tasks.ContentRangeFossologyLicense
    - swh.indexer.tasks.ContentRangeMimetype
    - swh.indexer.tasks.Ctags
    - swh.indexer.tasks.OriginHead
    - swh.indexer.tasks.OriginMetadata
    - swh.indexer.tasks.RecomputeChecksums
    - swh.indexer.tasks.RevisionMetadata

journal:
  brokers:
    - kafka
  group_id: swh.indexer.journal_client
  prefix: swh.journal.objects
max_messages: 50

tools:
  name: swh-metadata-detector
  version: 0.0.2
  configuration: {}
