scheduler:
  cls: remote
  url: http://swh-scheduler:5008/

celery:
  broker_heartbeat: null
  task_broker: amqp://guest:guest@amqp//
  task_queues:
    - swh.lister.arch.tasks.ArchListerTask
    - swh.lister.aur.tasks.AurListerTask
    - swh.lister.bitbucket.tasks.FullBitBucketRelister
    - swh.lister.bitbucket.tasks.IncrementalBitBucketLister
    - swh.lister.bitbucket.tasks.RangeBitBucketLister
    - swh.lister.bower.tasks.BowerListerTask
    - swh.lister.cgit.tasks.CGitListerTask
    - swh.lister.conda.tasks.CondaListerTask
    - swh.lister.cpan.tasks.CpanListerTask
    - swh.lister.cran.tasks.CRANListerTask
    - swh.lister.crates.tasks.CratesListerTask
    - swh.lister.debian.tasks.DebianListerTask
    - swh.lister.fedora.tasks.FullFedoraRelister
    - swh.lister.gitea.tasks.FullGiteaRelister
    - swh.lister.gitea.tasks.IncrementalGiteaLister
    - swh.lister.gitea.tasks.RangeGiteaLister
    - swh.lister.github.tasks.FullGitHubRelister
    - swh.lister.github.tasks.IncrementalGitHubLister
    - swh.lister.github.tasks.RangeGitHubLister
    - swh.lister.gitiles.tasks.GitilesListerTask
    - swh.lister.gitlab.tasks.FullGitLabRelister
    - swh.lister.gitlab.tasks.IncrementalGitLabLister
    - swh.lister.gitlab.tasks.RangeGitLabLister
    - swh.lister.gitweb.tasks.GitwebListerTask
    - swh.lister.gnu.tasks.GNUListerTask
    - swh.lister.gogs.tasks.FullGogsRelister
    - swh.lister.golang.tasks.FullGolangLister
    - swh.lister.hackage.tasks.HackageListerTask
    - swh.lister.launchpad.tasks.IncrementalLaunchpadLister
    - swh.lister.launchpad.tasks.FullLaunchpadLister
    - swh.lister.maven.tasks.FullMavenLister
    - swh.lister.nixguix.tasks.NixGuixListerTask
    - swh.lister.npm.tasks.NpmIncrementalListerTask
    - swh.lister.npm.tasks.NpmListerTask
    - swh.lister.nuget.tasks.NugetListerTask
    - swh.lister.opam.tasks.OpamListerTask
    - swh.lister.packagist.tasks.PackagistListerTask
    - swh.lister.pagure.tasks.PagureListerTask
    - swh.lister.phabricator.tasks.FullPhabricatorLister
    - swh.lister.phabricator.tasks.IncrementalPhabricatorLister
    - swh.lister.pubdev.tasks.PubDevListerTask
    - swh.lister.puppet.tasks.PuppetListerTask
    - swh.lister.pypi.tasks.PyPIListerTask
    - swh.lister.rubygems.tasks.RubyGemsListerTask
    - swh.lister.sourceforge.tasks.FullSourceForgeLister
    - swh.lister.sourceforge.tasks.IncrementalSourceForgeLister
    - swh.lister.stagit.tasks.StagitListerTask
