storage:
  cls: remote
  args:
    url: http://swh-storage:5002/

scheduler:
  cls: remote
  args:
    url: http://swh-scheduler:5008/

lister:
  cls: local
  args:
    db: postgresql://postgres@swh-listers-db/swh-listers

celery:
  task_broker: amqp://guest:guest@amqp//
  task_queues:
    - swh.lister.bitbucket.tasks.FullBitBucketRelister
    - swh.lister.bitbucket.tasks.IncrementalBitBucketLister
    - swh.lister.bitbucket.tasks.RangeBitBucketLister
    - swh.lister.cgit.tasks.CGitListerTask
    - swh.lister.cran.tasks.CRANListerTask
    - swh.lister.debian.tasks.DebianListerTask
    - swh.lister.gitea.tasks.FullGiteaRelister
    - swh.lister.gitea.tasks.IncrementalGiteaLister
    - swh.lister.gitea.tasks.RangeGiteaLister
    - swh.lister.github.tasks.FullGitHubRelister
    - swh.lister.github.tasks.IncrementalGitHubLister
    - swh.lister.github.tasks.RangeGitHubLister
    - swh.lister.gitlab.tasks.FullGitLabRelister
    - swh.lister.gitlab.tasks.IncrementalGitLabLister
    - swh.lister.gitlab.tasks.RangeGitLabLister
    - swh.lister.gnu.tasks.GNUListerTask
    - swh.lister.npm.tasks.NpmIncrementalListerTask
    - swh.lister.npm.tasks.NpmListerTask
    - swh.lister.launchpad.tasks.IncrementalLaunchpadLister
    - swh.lister.launchpad.tasks.FullLaunchpadLister
    - swh.lister.launchpad.tasks.NewLaunchpadLister
    - swh.lister.packagist.tasks.PackagistListerTask
    - swh.lister.phabricator.tasks.FullPhabricatorLister
    - swh.lister.phabricator.tasks.IncrementalPhabricatorLister
    - swh.lister.pypi.tasks.PyPIListerTask
