default_filename: archive.tar
storage:
  cls: pipeline
  steps:
    - cls: buffer
      min_batch_size:
        content: 10000
        content_bytes: 104857600
        directory: 1000
        revision: 1000
    - cls: filter
    - cls: remote
      url: http://nginx:5080/storage

celery:
  broker_heartbeat: null
  task_broker: amqp://guest:guest@amqp//
  task_queues:
    - swh.loader.package.deposit.tasks.LoadDeposit
    - swh.deposit.loader.tasks.ChecksDepositTsk

deposit:
  url: http://nginx:5080/deposit/1/private
  auth:
    username: test
    password: test

url: http://nginx:5080/deposit
