storage:
  cls: pipeline
  steps:
    - cls: buffer
      min_batch_size:
        content: 10000
        content_bytes: 104857600
        directory: 1000
        revision: 1000
    - cls: filter
    - cls: remote
      url: http://swh-storage:5002/

celery:
  task_broker: amqp://guest:guest@amqp//
  task_queues:
    - swh.loader.package.opam.tasks.LoadOpam

initialize_opam_root: True
