# see:
# - http://cassandra.apache.org/doc/latest/operating/metrics.html
# - https://blog.pythian.com/step-step-monitoring-cassandra-prometheus-grafana/

startDelaySeconds: 0
hostPort: cassandra-seed:7199
username:
password:
#jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:1234/jmxrmi
ssl: false
lowercaseOutputName: false
lowercaseOutputLabelNames: false
whitelistObjectNames: ["org.apache.cassandra.metrics:*"]
blacklistObjectNames: []
rules:
- pattern: org.apache.cassandra.metrics<type=(Connection|Streaming), scope=(\S*), name=(\S*)><>(Count|Value)
  name: cassandra_$1_$3
  labels:
    address: "$2"
- pattern: org.apache.cassandra.metrics<type=(ColumnFamily), name=(RangeLatency)><>(Mean)
  name: cassandra_$1_$2_$3
- pattern: org.apache.cassandra.net<type=(FailureDetector)><>(DownEndpointCount)
  name: cassandra_$1_$2
- pattern: org.apache.cassandra.metrics<type=(Keyspace), keyspace=(\S*), name=(\S*)><>(Count|Mean|95thPercentile)
  name: cassandra_$1_$3_$4
  labels:
    "$1": "$2"
- pattern: org.apache.cassandra.metrics<type=(Table), keyspace=(\S*), scope=(\S*), name=(\S*)><>(Count|Mean|95thPercentile)
  name: cassandra_$1_$4_$5
  labels:
    "keyspace": "$2"
    "table": "$3"
- pattern: org.apache.cassandra.metrics<type=(ClientRequest), scope=(\S*), name=(\S*)><>(Count|Mean|95thPercentile)
  name: cassandra_$1_$3_$4
  labels:
    "type": "$2"
- pattern: org.apache.cassandra.metrics<type=(\S*)(?:, ((?!scope)\S*)=(\S*))?(?:, scope=(\S*))?,
    name=(\S*)><>(Count|Value)
  name: cassandra_$1_$5
  labels:
    "$1": "$4"
    "$2": "$3"
