scheduler:
  cls: local
  db: postgresql:///?service=swh-scheduler
celery:
  broker_heartbeat: null
  task_broker: amqp://guest:guest@amqp/%2f
  broker_transport_options:
    max_retries: 1
no_origins_scheduled_backoff: 60
# Ensure origins without last update get scheduled a bit too (e.g. opam,
# bower, ...)
scheduling_policy:
  default:
    - policy: never_visited_oldest_update_first
      weight: 40
    - policy: never_visited_oldest_update_first
      weight: 40
    - policy: origins_without_last_update
      weight: 20
