scheduler:
  cls: local
  db: postgresql:///?service=swh-scheduler
celery:
  broker_heartbeat: null
  task_broker: amqp://guest:guest@amqp/%2f
  broker_transport_options:
    max_retries: 1
no_origins_scheduled_backoff: 60
# ensure opam origin loading tasks will be scheduled
scheduling_policy:
  opam:
    - policy: origins_without_last_update
      weight: 100
