scheduler:
  cls: local
  db: postgresql:///?service=swh-scheduler
celery:
  broker_heartbeat: null
  task_broker: amqp://guest:guest@amqp/%2f
  broker_transport_options:
    max_retries: 1
no_origins_scheduled_backoff: 60
scheduling_policy:
  git:
    # override git origin scheduling policies, same as default ones
    # but without table sampling
    - policy: already_visited_order_by_lag
      weight: 49
    - policy: never_visited_oldest_update_first
      weight: 49
    - policy: origins_without_last_update
      weight: 2
