storage:
  cls: cassandra
  hosts:
    - cassandra-seed
  keyspace: swh
  objstorage:
    cls: remote
    url: http://swh-objstorage:5003/
  journal_writer:
    cls: kafka
    brokers:
      - kafka
    prefix: swh.journal.objects
    client_id: swh.storage.master
    anonymize: true
