storage:
  cls: postgresql
  db: postgresql:///?service=swh-storage
  objstorage:
    cls: remote
    url: http://nginx:5080/objstorage
  journal_writer:
    cls: kafka
    brokers:
      - kafka
    prefix: swh.journal.objects
    client_id: swh.storage.master
    anonymize: true
