storage:
  cls: postgresql
  db: postgresql:///?service=swh-storage-mirror
  objstorage:
    cls: remote
    url: http://nginx:5080/objstorage

journal_client:
  cls: kafka
  brokers:
    - kafka
  prefix: swh.journal.objects
  group_id: swh.storage.mirror.replayer
  privileged: true

journal_writer:
  brokers:
    - kafka
  prefix: swh.journal.objects
  client_id: swh.journal.backfiller
