storage:
  cls: remote
  url: http://nginx:5080/storage
scheduler:
  cls: remote
  url: http://nginx:5080/scheduler
vault:
  cls: postgresql
  db: postgresql:///?service=swh-vault
cache:
  cls: pathslicing
  root: /srv/softwareheritage/vault
  slicing: 0:5
smtp:
  port: 1025
  host: mailhog
