storage:
  cls: remote
  url: http://swh-storage-read-replica:5002/
scheduler:
  cls: remote
  url: http://swh-scheduler:5008/
vault:
  cls: postgresql
  db: postgresql:///?service=swh-vault
cache:
  cls: pathslicing
  root: /srv/softwareheritage/vault
  slicing: 0:5
