storage:
  cls: remote
  url: http://swh-storage:5002/
scheduler:
  cls: remote
  url: http://swh-scheduler:5008/
vault:
  cls: local
  args:
    db: postgresql:///?service=swh-vault
cache:
  cls: pathslicing
  root: /srv/softwareheritage/vault
  slicing: 0:5
