storage:
  cls: remote
  url: http://nginx:5080/storage
  timeout: 1

objstorage:
  cls: remote
  url: http://nginx:5080/objstorage

indexer_storage:
  cls: remote
  url: http://nginx:5080/indexer-storage

scheduler:
  cls: remote
  url: http://nginx:5080/scheduler

vault:
  cls: remote
  args:
    url: http://nginx:5080/vault

deposit:
  private_api_url: http://nginx:5080/deposit/1/private/
  private_api_user: swhworker
  private_api_password: ""

allowed_hosts:
  - "*"

debug: yes

serve_assets: yes

development_db: /tmp/swh/web.sqlite3

production_db:
  host: swh-web-db
  port: 5432
  name: swh-web
  user: postgres
  password: testpassword

throttling:
  cache_uri: memcache:11211
  scopes:
    swh_api:
      limiter_rate:
        default: 120/h
    swh_api_origin_search:
      limiter_rate:
        default: 70/m
    swh_api_origin_visit_latest:
      limiter_rate:
        default: 700/m
    swh_vault_cooking:
      limiter_rate:
        default: 120/h
    swh_save_origin:
      limiter_rate:
        default: 120/h

search:
  cls: remote
  url: http://nginx:5080/search

search_config:
  metadata_backend: swh-search

keycloak:
  server_url: http://nginx:5080/keycloak/auth/
  realm_name: SoftwareHeritage
instance_name: archive-docker.softwareheritage.org

save_code_now_webhook_secret: whsec_QgEXGNJPBPjKsyBMPwtAkJpgVtA0g41A