storage:
  cls: remote
  args:
    url: http://swh-storage-mirror:5002/
    timeout: 1

objstorage:
  cls: remote
  args:
    url: http://swh-objstorage:5003/

indexer_storage:
  cls: remote
  args:
    url: http://swh-idx-storage:5007/

scheduler:
  cls: remote
  args:
    url: http://swh-scheduler:5008/

vault:
  cls: remote
  args:
    url: http://swh-vault:5005/

deposit:
  private_api_url: https://swh-deposit:5006/1/private/
  private_api_user: swhworker
  private_api_password: ''

allowed_hosts:
  - "*"

debug: yes

serve_assets: yes
