storage:
  cls: remote
  url: http://swh-storage-read-replica:5002/
  timeout: 1

indexer_storage:
  cls: remote
  url: http://swh-idx-storage:5007/

scheduler:
  cls: remote
  url: http://swh-scheduler:5008/

vault:
  cls: remote
  args:
    url: http://swh-vault:5005/

deposit:
  private_api_url: https://swh-deposit:5006/1/private/
  private_api_user: swhworker
  private_api_password: ""

allowed_hosts:
  - "*"

debug: yes

serve_assets: yes

development_db: /tmp/swh/web.sqlite3

production_db:
  host: swh-web-db
  port: 5432
  name: swh-web
  user: postgres
  password: testpassword

throttling:
  cache_uri: 127.0.0.1:11211
  scopes:
    swh_api:
      limiter_rate:
        default: 120/h
      exempted_networks:
        - 0.0.0.0/0
    swh_api_origin_search:
      limiter_rate:
        default: 70/m
      exempted_networks:
        - 0.0.0.0/0
    swh_api_origin_visit_latest:
      limiter_rate:
        default: 700/m
      exempted_networks:
        - 0.0.0.0/0
    swh_vault_cooking:
      limiter_rate:
        default: 120/h
      exempted_networks:
        - 0.0.0.0/0
    swh_save_origin:
      limiter_rate:
        default: 120/h
      exempted_networks:
        - 0.0.0.0/0

search: {}
