storage:
  cls: remote
  url: http://nginx:5080/storage
  timeout: 5

indexer_storage:
  cls: remote
  url: http://nginx:5080/indexer-storage

scheduler:
  cls: remote
  url: http://nginx:5080/scheduler

vault:
  cls: remote
  url: http://nginx:5080/vault

deposit:
  private_api_url: http://nginx:5080/deposit/1/private/
  private_api_user: swhworker
  private_api_password: ""

allowed_hosts:
  - "*"

debug: yes

serve_assets: yes

development_db: /tmp/swh/web.sqlite3

production_db:
  name: postgresql:///?service=swh-web

throttling:
  cache_uri: memcache:11211
  scopes:
    swh_api:
      limiter_rate:
        default: 120/h
      exempted_networks:
        - 0.0.0.0/0
    swh_api_origin_search:
      limiter_rate:
        default: 70/m
      exempted_networks:
        - 0.0.0.0/0
    swh_api_origin_visit_latest:
      limiter_rate:
        default: 700/m
      exempted_networks:
        - 0.0.0.0/0
    swh_vault_cooking:
      limiter_rate:
        default: 120/h
      exempted_networks:
        - 0.0.0.0/0
    swh_save_origin:
      limiter_rate:
        default: 120/h
      exempted_networks:
        - 0.0.0.0/0

instance_name: archive-docker.softwareheritage.org

search:
  cls: remote
  url: http://nginx:5080/search

search_config:
  metadata_backend: swh-search

counters:
  cls: remote
  url: http://nginx:5080/counters
counters_backend: swh-counters
history_counters_url: http://nginx:5080/counters/counters_history/history.json

save_code_now_webhook_secret: whsec_QgEXGNJPBPjKsyBMPwtAkJpgVtA0g41A
